import { fitRecordBody, neutraliseMarkers, parseMarker, recordBodyProblem, renderMarker, signBody, signatureLine } from "#conventions.js";

describe("the line that signs what an agent wrote", () => {
  it("names the model and the effort", () => {
    expect(signatureLine("claude-opus-5-5", "medium")).toBe("// Generated by AI (claude-opus-5-5:medium)");
    expect(signatureLine("claude-haiku-4-5-20251001", "high")).toBe("// Generated by AI (claude-haiku-4-5-20251001:high)");
  });

  it("says unknown for a model nobody reported or configured, and default for no effort", () => {
    expect(signatureLine(null, null)).toBe("// Generated by AI (unknown:default)");
    expect(signatureLine("gpt-5.1", null)).toBe("// Generated by AI (gpt-5.1:default)");
  });

  it.each([
    ["Markdown", "**bold**"],
    ["a link", "[x](https://example.com)"],
    ["a marker", '<!-- landrace {"stage":"s","kind":"output","round":1} -->'],
    ["a new line", "opus\n\nhi"],
    ["a closing paren", "opus) and more ("],
    ["nothing", ""],
  ])("prints unknown for a model with %s in it", (_what, model) => {
    expect(signatureLine(model, "low")).toBe("// Generated by AI (unknown:low)");
  });

  it("prints unknown for an effort outside the plain set too", () => {
    expect(signatureLine("opus", "<b>max</b>")).toBe("// Generated by AI (opus:unknown)");
  });

  it("goes last, after a blank line, and the marker after it is still the one read", () => {
    const line = signatureLine("opus", "low");
    const signed = signBody("The answer.\n", line);
    expect(signed).toBe(`The answer.\n\n${line}`);
    const posted = neutraliseMarkers(signed) + renderMarker({ stage: "s", kind: "output", round: 1 });
    expect(parseMarker(posted)).toMatchObject({ stage: "s", kind: "output", round: 1 });
    expect(neutraliseMarkers(signed)).toBe(signed);
  });

  it("leaves a body with nothing in it, and a body when signing is off, as they are", () => {
    expect(signBody("  \n", signatureLine("opus", "low"))).toBe("  \n");
    expect(signBody("The answer.", null)).toBe("The answer.");
  });

  it("keeps the line on a body cut to fit a record", () => {
    const line = signatureLine("opus", "low");
    const fitted = fitRecordBody("x".repeat(40_000), line);
    expect(fitted.endsWith(`\n\n${line}`)).toBe(true);
    expect(recordBodyProblem(fitted)).toBeNull();
    // A body that fits alone and not with the line is cut too, never posted over the cap.
    const edge = "y".repeat(32 * 1024 - 5);
    expect(recordBodyProblem(edge)).toBeNull();
    expect(recordBodyProblem(fitRecordBody(edge, line))).toBeNull();
    expect(fitRecordBody("short", line)).toBe(`short\n\n${line}`);
  });
});
