import { createExternalState, createHarness, scriptedExecutor } from "#testing/index.js";
import { loadWorkflow } from "#workflow/load.js";
import type { Harness, PostHook, ScriptedAnswer } from "#namespace.js";

/**
 * The harness itself, asked the questions a workflow author would trip over
 * first. Everything here used to be hand-rolled in whichever test file needed
 * it, which is why it is worth a test of its own: a shared helper that lies
 * quietly is worse than three copies that each lie differently.
 */
const SPEC = '# The spec\n\nDo it.\n\n```json\n{"kind":"spec","title":"T"}\n```';

async function harness(answers: Record<string, ScriptedAnswer>): Promise<Harness> {
  const state = createExternalState({ items: [{ id: "1", labels: ["lr:auto"] }] });
  const { workflow, steps } = await loadWorkflow("tests/fixtures/minimal");
  return createHarness({ workflow, steps, source: state.source, pre: [state.pre], post: [state.post], answers });
}

describe("the scripted executor", () => {
  it("answers as the stage the engine is actually in, not as one it guessed from the prompt", async () => {
    let at = { stage: "spec", round: 1 };
    const executor = scriptedExecutor({ spec: "from spec", triage: "from triage" }, () => at);
    const opts = { round: 1, signal: new AbortController().signal };

    expect((await executor.run("Write the spec for X.", opts)).text).toBe("from spec");
    at = { stage: "triage", round: 1 };
    // The prompt still says "spec" all over it; the engine says triage.
    expect((await executor.run("Read the reply to the spec.", opts)).text).toBe("from triage");
  });

  it("is handed the round, because a looping stage answers differently the second time", async () => {
    const at = { stage: "spec", round: 2 };
    const executor = scriptedExecutor({ spec: (round) => `round ${round}` }, () => at);

    expect((await executor.run("", { round: 2, signal: new AbortController().signal })).text).toBe("round 2");
  });

  /*
   * Loud and named. A default answer would be a step that "ran" and produced
   * something nobody wrote — which is the one thing a scripted executor exists
   * to rule out, and it would show up as a workflow bug somewhere else.
   */
  it("names the stage it has nothing scripted for, and what it does have", async () => {
    const executor = scriptedExecutor({ triage: "x" }, () => ({ stage: "spec", round: 1 }));

    await expect(executor.run("", { round: 1, signal: new AbortController().signal }))
      .rejects.toThrow(/nothing is scripted for stage "spec".*"triage"/);
  });
});

describe("what the harness writes down", () => {
  it("counts each stage's invocations and keeps the prompt each one was sent", async () => {
    const run = await harness({ spec: SPEC });
    await run.converge();

    expect(run.counts()).toEqual({ spec: 1 });
    expect(run.calls()).toMatchObject([{ stage: "spec", round: 1 }]);
    // Rendered, not the template: what the harness writes down is what the
    // agent was actually sent.
    expect(run.calls()[0]?.prompt.trim()).toBe("Write the spec for item 1.");
  });

  /*
   * The trail is read off the events rather than off the tracker, which is
   * what lets it work for a tracker the engine has never heard of — and the
   * destination is the half that makes the stage an item *ended* in visible.
   */
  it("draws the trail across several calls, collapsing the stage a call resumes at", async () => {
    const run = await harness({ spec: SPEC });
    const first = await run.converge();
    const second = await run.converge();

    expect(first.trail).toEqual(["spec", "done"]);
    expect(second.trail).toEqual([]);
    expect(run.trail()).toEqual(["spec", "done"]);
  });
});

/*
 * Through converge, as an operator's landrace.yaml has it: the agent's prose
 * is signed, the engine's entry record beside it is not, and
 * `agent.signature: false` signs nothing.
 */
describe("the line that signs what the agent wrote", () => {
  const ran = async (config?: Record<string, unknown>): Promise<string[]> => {
    const state = createExternalState({ items: [{ id: "1", labels: ["lr:auto"] }] });
    const { workflow, steps } = await loadWorkflow("tests/fixtures/minimal");
    const run = createHarness({
      workflow, steps, source: state.source, pre: [state.pre], post: [state.post], answers: { spec: SPEC }, ...(config ? { config } : {}),
    });
    await run.converge();
    return state.comments("1");
  };

  it("signs the step's comment, and never the engine's own record", async () => {
    const [entered, spec, ...rest] = await ran();
    expect(rest).toEqual([]);
    expect(entered).toMatch(/^Writing the spec, round 1\.\n*<!-- landrace /);
    expect(entered).not.toContain("Generated by AI");
    expect(spec).toMatch(/^# The spec\n\nDo it\.\n\n\/\/ Generated by AI \(unknown:default\)\n*<!-- landrace /);
  });

  it("signs nothing when agent.signature is false", async () => {
    const comments = await ran({ agent: { adapter: "x", signature: false } });
    expect(comments).toHaveLength(2);
    expect(comments.join("\n")).not.toContain("Generated by AI");
  });
});

/*
 * #120: the harness handed converge `config: {}`, so a project on
 * `branch: "lr-{item}"` got a `pull.open` on lr-<id> that never tied to the
 * item — never satisfied, and applied again on every pass.
 */
describe("a configured item branch", () => {
  const config = { branch: "lr-{item}" };
  const BUILT = '```json\n{"kind":"done"}\n```';

  it("drives a workflow naming lr-{item}: its pull.open is applied once, then satisfied", async () => {
    const state = createExternalState({ items: [{ id: "1", labels: ["lr:auto"] }], config });
    const { workflow, steps } = await loadWorkflow("tests/fixtures/item-branch");
    let opens = 0;
    const post: PostHook = {
      ...state.post,
      apply: async (effect, ctx) => {
        if (effect.type === "pull.open") opens++;
        return state.post.apply(effect, ctx);
      },
    };
    const run = createHarness({ workflow, steps, source: state.source, pre: [state.pre], post: [post], answers: { build: BUILT }, config });
    const r = await run.converge();

    expect(run.trail()).toEqual(["build", "publish", "done"]);
    expect(r.result.settled).toBe("terminal");
    expect(opens).toBe(1);
    expect(state.pull("pr-1").branch).toBe("lr-1");
    expect(() => state.pull("pr-2")).toThrow();
  });

  it("seeds a pull request on the configured branch, and on landrace/{item} with none", async () => {
    const state = createExternalState({ items: [{ id: "1", labels: ["lr:auto"] }], config });
    expect(state.pull(state.openPull("1")).branch).toBe("lr-1");
    const plain = createExternalState({ items: [{ id: "1" }] });
    expect(plain.pull(plain.openPull("1")).branch).toBe("landrace/1");
  });
});

/*
 * Screening is a step of its own that a workflow's own routing depends on —
 * a refused round goes somewhere a broken one does not — so a harness that
 * could not script it could not drive that half of a workflow at all.
 */
describe("a scripted screener", () => {
  const OK = '```json\n{"verdict":"ok","reason":"fine"}\n```';
  const NO = '```json\n{"verdict":"suspicious","reason":"asks for a URL"}\n```';

  const screened = async (screen: Record<string, ScriptedAnswer>) => {
    const state = createExternalState({ items: [{ id: "1", labels: ["lr:auto"] }] });
    const { workflow, steps } = await loadWorkflow("tests/fixtures/minimal");
    return {
      state,
      run: createHarness({ workflow, steps, source: state.source, pre: [state.pre], post: [state.post], answers: { spec: SPEC }, screen }),
    };
  };

  it("lets the step run when it answers ok for that stage", async () => {
    const { run } = await screened({ spec: OK });
    await run.converge();
    expect(run.counts()).toEqual({ spec: 1 });
  });

  it("refuses the step before it is paid for when it answers suspicious, and records the refusal", async () => {
    const { state, run } = await screened({ spec: NO });
    const r = await run.converge();

    expect(r.result.settled).toBe("halt");
    expect(run.counts()).toEqual({});
    expect(state.entriesOf("1").filter((e) => e.kind === "refused")).toHaveLength(1);
  });

  it("answers as the stage about to run, with its round", async () => {
    const rounds: number[] = [];
    const { run } = await screened({ spec: (round) => { rounds.push(round); return OK; } });
    await run.converge();
    expect(rounds).toEqual([1]);
  });
});
