import { runStep, settleOutput } from "#runner/step.js";
import { neutraliseMarkers, parseMarker, renderMarker, signatureLine } from "#conventions.js";
import type { Effect, Executor, ExecutorAnswer, Snapshot, Step, StepResult } from "#namespace.js";

type Ok = Extract<StepResult, { ok: true }>;

const snapshot = { item: { number: 7, title: "Add export" }, run: { counters: {} } } as unknown as Snapshot;
const answering = (text: string, said: Partial<ExecutorAnswer> = {}): Executor =>
  ({ id: "f", run: async () => ({ text, sessionId: "sid", ...said }) });
const json = (value: object, prose = "What the agent wrote.") => `${prose}\n\n\`\`\`json\n${JSON.stringify(value)}\n\`\`\``;

const LINE = "// Generated by AI (claude-opus-5-5:medium)";

const spec: Step = {
  prompt: "Write the spec.",
  output: {
    discriminator: "kind",
    shapes: { questions: {}, spec: {} },
    routes: [
      { when: { kind: "questions" }, effect: { type: "tracker.comment", marker: "questions:{round}" } },
      { when: { kind: "spec" }, effect: { type: "artifact.publish", artifact: "spec" } },
    ],
  },
};

const run = (text: string, over: Partial<Parameters<typeof runStep>[0]> = {}, said: Partial<ExecutorAnswer> = { model: "claude-opus-5-5", effort: "medium" }) =>
  runStep({ item: "1", step: spec, stageId: "spec", round: 2, snapshot, executor: answering(text, said), signal: new AbortController().signal, ...over }) as Promise<Ok>;

const bodyOf = (e: Effect | undefined): string => String(e?.body);

describe("signing what an agent wrote", () => {
  describe("the model and the effort", () => {
    it("names the model the run answered with, and carries it on the result", async () => {
      const r = await run(json({ kind: "questions" }));
      expect(r.model).toBe("claude-opus-5-5");
      expect(bodyOf(r.effects[0])).toBe(`What the agent wrote.\n\n${LINE}`);
    });

    it("falls back to the step's model, then to unknown; to the step's effort, then to default", async () => {
      const own = await run(json({ kind: "questions" }), { step: { ...spec, model: "haiku", effort: "high" } }, {});
      expect(bodyOf(own.effects[0])).toMatch(/\/\/ Generated by AI \(haiku:high\)$/);
      expect(own.model).toBe("haiku");
      const none = await run(json({ kind: "questions" }), {}, {});
      expect(bodyOf(none.effects[0])).toMatch(/\/\/ Generated by AI \(unknown:default\)$/);
      expect(none.model).toBeNull();
    });

    it("prints unknown for a model carrying Markdown or a marker", async () => {
      const marker = renderMarker({ stage: "spec", kind: "output", round: 9 });
      for (const model of ["**opus**", marker]) {
        const r = await run(json({ kind: "questions" }), {}, { model, effort: "low" });
        expect(bodyOf(r.effects[0])).toMatch(/\/\/ Generated by AI \(unknown:low\)$/);
      }
    });

    it("signs nothing when signing is off", async () => {
      const r = await run(json({ kind: "questions" }), { signature: false });
      expect(bodyOf(r.effects[0])).toBe("What the agent wrote.");
      expect(r.model).toBe("claude-opus-5-5");
    });
  });

  describe("each surface", () => {
    it("signs a tracker comment of the step's prose, and its marker is still the one read once posted", async () => {
      const r = await run(json({ kind: "questions" }));
      const posted = neutraliseMarkers(bodyOf(r.effects[0])) + renderMarker({ stage: "spec", kind: "output", round: 2, marker: "questions:2" });
      expect(parseMarker(posted)).toMatchObject({ stage: "spec", round: 2, marker: "questions:2" });
      expect(posted.indexOf(LINE)).toBeLessThan(posted.indexOf("<!--"));
    });

    it("signs the spec it publishes as its last line, and never the record beside it", async () => {
      const r = await run(json({ kind: "spec" }, "# Spec\n\nThe design."));
      expect(r.effects.map((e) => e.type)).toEqual(["artifact.publish", "tracker.comment"]);
      expect(bodyOf(r.effects[0])).toBe(`# Spec\n\nThe design.\n\n${LINE}`);
      expect(bodyOf(r.effects[1])).toBe('Recorded the output of "spec", round 2.');
    });

    const routed: Step = {
      prompt: "triage",
      output: {
        discriminator: "kind",
        shapes: { answered: { reply: "string" } },
        routes: [{
          when: { kind: "answered" },
          effects: [
            { type: "tracker.comment", from: "reply" },
            { type: "tracker.comment" },
            { type: "tracker.comment", body: "Triaged in round {round}." },
            { type: "tracker.create", title: "Follow-up" },
            { type: "tracker.field", fields: { severity: "high" } },
          ],
        }],
      },
    };

    it("signs a part fed from an answer field or the prose, and never one the workflow wrote, an issue body or a field", () => {
      const r = settleOutput({
        step: routed, item: "7", stageId: "triage", round: 3, text: json({ kind: "answered", reply: "Try restarting." }),
        sessionId: null, by: "agent", signature: LINE,
      }) as Ok;
      expect(r.effects.map(bodyOf)).toEqual([
        `Try restarting.\n\n${LINE}`,
        `What the agent wrote.\n\n${LINE}`,
        "Triaged in round 3.",
        "What the agent wrote.",
        "What the agent wrote.",
        'Recorded the output of "triage", round 3.',
      ]);
    });

    it("signs a review's own body, each finding's thread and each reply, and leaves the recorded value as the agent gave it", () => {
      const review: Step = {
        prompt: "review",
        output: {
          discriminator: "kind",
          shapes: { reviewed: { findings: "array", replies: "array", resolved: "array" } },
          routes: [{ when: { kind: "reviewed" }, effect: { type: "pull.review", branch: "landrace/{item}", marker: "review:{round}" } }],
        },
      };
      const value = {
        kind: "reviewed",
        findings: [{ file: "src/a.ts", line: 3, body: "Off by one." }, "not a finding"],
        replies: [{ thread: "t1", body: "Fixed in abc." }],
        resolved: ["t2"],
      };
      const r = settleOutput({
        step: review, item: "7", stageId: "review", round: 1, text: json(value, "Two things."), sessionId: null, by: "agent", signature: LINE,
      }) as Ok;
      const [destination, record] = r.effects;
      expect(bodyOf(destination)).toBe(`Two things.\n\n${LINE}`);
      expect(destination?.output).toEqual({
        ...value,
        findings: [{ file: "src/a.ts", line: 3, body: `Off by one.\n\n${LINE}` }, "not a finding"],
        replies: [{ thread: "t1", body: `Fixed in abc.\n\n${LINE}` }],
      });
      expect(record?.output).toEqual(value);
      expect(bodyOf(record)).toBe('Recorded the output of "review", round 1.');
    });

    it("signs nothing a step writes when it is handed no line", () => {
      const r = settleOutput({ step: spec, item: "7", stageId: "spec", round: 1, text: json({ kind: "spec" }), sessionId: null, by: "agent" }) as Ok;
      expect(bodyOf(r.effects[0])).toBe("What the agent wrote.");
    });
  });

  it("builds the line from the conventions' one function", () => {
    expect(LINE).toBe(signatureLine("claude-opus-5-5", "medium"));
  });
});
