import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { repositoryRoot } from "#agent/worktree.js";
import { messageOf } from "#runner/errors.js";
import type { McpServer, Problem, ResolvedMcp } from "#namespace.js";

/**
 * One server as `.mcp.json` defines it. Only the fields the operator-server
 * check reads are typed; everything else — `type`, `url`, `headers` — passes
 * through untouched, because the definition is handed to the agent as it was
 * written, never rebuilt from the parts this file happens to understand.
 */
export const mcpServerSchema = z
  .object({
    command: z.string().optional(),
    args: z.array(z.string()).optional(),
    env: z.record(z.string()).optional(),
  })
  .passthrough();

export const mcpConfigSchema = z.object({ mcpServers: z.record(mcpServerSchema) });

/** The name agsync gives the operator server, and the one the executor reserves for a step's create_child server. */
const OPERATOR_NAME = "landrace";

/**
 * `landrace mcp` however it is spelled: the bin, `npx landrace@<tag>`, the
 * built `cli.js`, the source entry, or any of those inside a shell's `-c`.
 * Matched on the whole command line, so wrapping it in `sh` hides nothing.
 * Broad on purpose: refusing a server that merely resembles it costs the
 * operator a rename, and letting the real one through hands a step agent the
 * tools that move tickets.
 */
const RUNS_OPERATOR = /(?:^|[\s/\\])(?:landrace(?:@\S*)?|cli\.[cm]?[jt]s|cli[/\\]index\.[cm]?[jt]s)\s+mcp(?:\s|$)/;

const runsOperator = (server: McpServer): boolean =>
  RUNS_OPERATOR.test([server.command ?? "", ...(server.args ?? [])].join(" "));

/** Said once, because both ways of naming the operator server are refused for the same reason. */
const operatorProblem = (name: string, how: string): Problem => ({
  rule: "mcp",
  message:
    `agent.mcp names "${name}", ${how} landrace's own operator server: its tools create, update and reply on ` +
    "tickets — a step holding them could move its own ticket — so operator tools must never reach a step agent",
});

/**
 * The servers `agent.mcp` allows, looked up by name in the repository root's
 * `.mcp.json` — once, at startup, never per step.
 *
 * The root and not the worktree a step runs in: the file is generated by
 * agsync and gitignored, so a worktree cut from HEAD never has it, and one
 * that did would be the repository's committed copy rather than the operator's.
 *
 * Every problem is a sentence about names and paths and nothing else. A
 * server's `env` or `args` may carry a credential, so neither is ever quoted —
 * and neither is the file's own text, which node's JSON.parse would otherwise
 * echo around a syntax error.
 */
export async function resolveStepServers(dir: string, names: readonly string[]): Promise<ResolvedMcp> {
  const wanted = [...new Set(names)];
  if (wanted.length === 0) return { servers: {}, problems: [] };

  // Refused on the name alone, before anything is read: this one needs no file
  // to be wrong, and a missing file must not hide it.
  const problems = wanted.filter((name) => name === OPERATOR_NAME).map((name) => operatorProblem(name, "which is"));
  const rest = wanted.filter((name) => name !== OPERATOR_NAME);
  if (rest.length === 0) return { servers: {}, problems };

  const fail = (message: string): ResolvedMcp => ({ servers: {}, problems: [...problems, { rule: "mcp", message }] });

  let root: string;
  try {
    root = await repositoryRoot(dir);
  } catch (e) {
    return fail(`agent.mcp names servers to look up in the repository root's .mcp.json, and there is no repository: ${messageOf(e)}`);
  }
  const file = join(root, ".mcp.json");

  let text: string;
  try {
    text = await readFile(file, "utf8");
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    return fail(
      code === "ENOENT"
        ? `agent.mcp names ${rest.map((n) => `"${n}"`).join(", ")}, but ${file} does not exist; \`agsync sync\` generates it`
        : `agent.mcp names servers, and ${file} could not be read (${code ?? "unknown error"})`,
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return fail(`${file} is not valid JSON; \`agsync sync\` regenerates it`);
  }
  const parsed = mcpConfigSchema.safeParse(raw);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    const where = issue?.path.length ? issue.path.join(".") : "mcpServers";
    return fail(`${file} is not an MCP config landrace can read: ${where}: ${issue?.message ?? "unexpected shape"}`);
  }

  const defined = parsed.data.mcpServers;
  const servers: Record<string, McpServer> = {};
  for (const name of rest) {
    const server = Object.hasOwn(defined, name) ? defined[name] : undefined;
    if (server === undefined) {
      const known = Object.keys(defined);
      problems.push({
        rule: "mcp",
        message:
          `agent.mcp names "${name}", which ${file} does not define` +
          (known.length ? ` — it defines ${known.join(", ")}` : " — it defines no servers"),
      });
    } else if (runsOperator(server)) {
      problems.push(operatorProblem(name, "whose command runs"));
    } else {
      servers[name] = server;
    }
  }
  return problems.length ? { servers: {}, problems } : { servers, problems };
}
