import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { ARG_SHAPE } from "#agent/claude.js";
import { repositoryRoot } from "#agent/worktree.js";
import { messageOf } from "#runner/errors.js";
import type { McpEntry, McpServer, Problem, ResolvedMcp } from "#namespace.js";

/**
 * One server as `.mcp.json` defines it. Only the fields the operator-server
 * check reads are typed; everything else — `type`, `url`, `headers` — passes
 * through untouched, because the definition is handed to the agent as it was
 * written, never rebuilt from the parts this file happens to understand.
 */
export const mcpServerSchema = z
  .object({
    command: z.string().optional(),
    args: z.array(z.string()).optional(),
    env: z.record(z.string()).optional(),
  })
  .passthrough();

export const mcpConfigSchema = z.object({ mcpServers: z.record(mcpServerSchema) });

/** The name agsync gives the operator server, and the one the executor reserves for a step's create_child server. */
const OPERATOR_NAME = "landrace";

/**
 * `landrace mcp` in the spellings a real configuration uses: the bin,
 * `npx landrace@<version>` or `landrace#<ref>`, the built `cli` entry with or
 * without its extension, the source entry, any of them quoted, with `--`
 * before the subcommand, or inside a shell's `-c` followed by `;`, `&` or `|`
 * — and in any case. Matched on the whole command line, so wrapping it in `sh`
 * hides nothing.
 *
 * Defence in depth over configuration the operator already trusts, not a
 * guarantee against every spelling: a wrapper script under another name gets
 * past it, and nothing could stop that short of running the server to ask.
 * Broad on purpose where it can be: refusing a server that merely resembles
 * it costs the operator a rename, and letting the real one through hands a
 * step agent the tools that move tickets.
 */
// In order: where a program name can start (the line, a space, a path
// separator, a quote or a shell operator); `landrace` with an npx-style
// version or ref, or the `cli` entry, built or source, with or without an
// extension; its closing quote, any `--` markers and `mcp`, quoted or not; and
// the end of that word (a space, the end, a quote or a shell operator).
const RUNS_OPERATOR =
  /(?:^|[\s/\\'"`;&|(])(?:landrace(?:[@#][^\s'"`;&|)]*)?|cli(?:[/\\]index)?(?:\.[cm]?[jt]s)?)['"`]?\s+(?:--\s+)*['"`]?mcp['"`]?(?=$|[\s;&|)'"`])/i;

const runsOperator = (server: McpServer): boolean =>
  RUNS_OPERATOR.test([server.command ?? "", ...(server.args ?? [])].join(" "));

/** Said once, because both ways of naming the operator server are refused for the same reason. */
const operatorProblem = (name: string, how: string): Problem => ({
  rule: "mcp",
  message:
    `agent.mcp names "${name}", ${how} landrace's own operator server: its tools create, update and reply on ` +
    "tickets — a step holding them could move its own ticket — so operator tools must never reach a step agent",
});

const shapeProblem = (what: string): Problem => ({
  rule: "mcp",
  message:
    `agent.mcp names ${what}, which the agent's command line cannot carry as one name: ` +
    "use letters, digits, '.', '_' and '-', starting with a letter or digit",
});

/**
 * The servers `agent.mcp` allows, looked up by name in the repository root's
 * `.mcp.json` — once, at startup, never per step.
 *
 * The root and not the worktree a step runs in: the file is generated by
 * agsync and gitignored, so a worktree cut from HEAD never has it, and one
 * that did would be the repository's committed copy rather than the operator's.
 *
 * Every problem is a sentence about names and paths and nothing else. A
 * server's `env` or `args` may carry a credential, so neither is ever quoted —
 * and neither is the file's own text, which node's JSON.parse would otherwise
 * echo around a syntax error.
 */
export async function resolveStepServers(dir: string, entries: readonly McpEntry[]): Promise<ResolvedMcp> {
  if (entries.length === 0) return { servers: {}, tools: {}, problems: [] };

  // Refused on the entries alone, before anything is read: these need no file
  // to be wrong, and a missing file must not hide them. A name reaches the
  // agent's argv as `mcp__<name>[__<tool>]` in `--allowedTools`, which the CLI
  // splits on spaces and commas — a server or tool called "x Bash" would allow
  // Bash — and `landrace` is both the operator server and the name the
  // executor gives a step's create_child server.
  const nameOf = (entry: McpEntry): string => (typeof entry === "string" ? entry : entry.name);
  const names = entries.map(nameOf);
  // Two entries for one server could disagree about its tools, and choosing
  // one of them would be "first match wins".
  const repeated = new Set(names.filter((name, i) => names.indexOf(name) !== i));
  const problems: Problem[] = [...repeated].map((name) => ({
    rule: "mcp",
    message: `agent.mcp names "${name}" more than once; name it once, with every tool a step may use on it`,
  }));
  const rest: string[] = [];
  const tools: Record<string, string[]> = {};
  for (const entry of entries) {
    const name = nameOf(entry);
    const listed = typeof entry === "string" ? undefined : entry.tools;
    const badTools = (listed ?? []).filter((tool) => !ARG_SHAPE.test(tool));
    if (repeated.has(name)) continue;
    if (!ARG_SHAPE.test(name)) problems.push(shapeProblem(`a server named ${JSON.stringify(name)}`));
    else if (name === OPERATOR_NAME) problems.push(operatorProblem(name, "which is"));
    else if (listed !== undefined && listed.length === 0) {
      problems.push({
        rule: "mcp",
        message:
          `agent.mcp names "${name}" with no tools, which would load the server and allow nothing on it; ` +
          "name it bare to allow every tool, or list the ones a step may use",
      });
    } else if (badTools.length) {
      problems.push(...badTools.map((tool) => shapeProblem(`a tool named ${JSON.stringify(tool)} on "${name}"`)));
    } else {
      rest.push(name);
      if (listed !== undefined) tools[name] = [...new Set(listed)];
    }
  }
  if (rest.length === 0) return { servers: {}, tools: {}, problems };

  const fail = (message: string): ResolvedMcp => ({ servers: {}, tools: {}, problems: [...problems, { rule: "mcp", message }] });

  let root: string;
  try {
    root = await repositoryRoot(dir);
  } catch (e) {
    return fail(`agent.mcp names servers to look up in the repository root's .mcp.json, and there is no repository: ${messageOf(e)}`);
  }
  const file = join(root, ".mcp.json");

  let text: string;
  try {
    text = await readFile(file, "utf8");
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    return fail(
      code === "ENOENT"
        ? `agent.mcp names ${rest.map((n) => `"${n}"`).join(", ")}, but ${file} does not exist; \`agsync sync\` generates it`
        : `agent.mcp names servers, and ${file} could not be read (${code ?? "unknown error"})`,
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return fail(`${file} is not valid JSON; \`agsync sync\` regenerates it`);
  }
  const parsed = mcpConfigSchema.safeParse(raw);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    const where = issue?.path.length ? issue.path.join(".") : "mcpServers";
    return fail(`${file} is not an MCP config landrace can read: ${where}: ${issue?.message ?? "unexpected shape"}`);
  }

  const defined = parsed.data.mcpServers;
  const servers: Record<string, McpServer> = {};
  for (const name of rest) {
    const server = Object.hasOwn(defined, name) ? defined[name] : undefined;
    if (server === undefined) {
      const known = Object.keys(defined);
      problems.push({
        rule: "mcp",
        message:
          `agent.mcp names "${name}", which ${file} does not define` +
          (known.length ? ` — it defines ${known.join(", ")}` : " — it defines no servers"),
      });
    } else if (runsOperator(server)) {
      problems.push(operatorProblem(name, "whose command runs"));
    } else {
      servers[name] = server;
    }
  }
  return problems.length ? { servers: {}, tools: {}, problems } : { servers, tools, problems };
}
